# Generated by Django 4.2.11 on 2024-06-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecolumn',
            name='column_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filecolumn',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_reader.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
